# Generated by Django 2.2.14 on 2020-08-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Cl', 'Clothing'), ('Co', 'Computing'), ('E', 'Electronics')], max_length=2),
        ),
    ]
