# Generated by Django 2.2.14 on 2020-08-21 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200820_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
